<?php

namespace AppBundle\Repository;

/**
 * BonodoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BonodoRepository extends \Doctrine\ORM\EntityRepository
{
}
